# Generated by Django 5.0.3 on 2024-05-07 15:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('meal_json', models.JSONField(verbose_name='meal_plan_json')),
                ('healthy_app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.healthyappuser', verbose_name='użytkownik healthy_app')),
            ],
        ),
    ]
