# Generated by Django 5.0.3 on 2024-05-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='healthy_app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.healthyappuser', verbose_name='użytkownik healthy_app'),
        ),
    ]
