# Generated by Django 5.0.3 on 2024-06-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_mealplan_healthy_app_user'),
        ('users', '0003_remove_healthyappuser_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='healthy_app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='użytkownik healthy_app'),
        ),
    ]
