# Generated by Django 5.0.3 on 2024-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_mealplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='general_health',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='general_max_kcal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='general_min_kcal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
