# Generated by Django 5.0.3 on 2024-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_mealplan_general_health_mealplan_general_max_kcal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='general_max_kcal',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='general_min_kcal',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
