# Generated by Django 5.0.3 on 2024-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_alter_mealplan_general_max_kcal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='photo',
            field=models.ImageField(default='default_plate.jpg', upload_to=''),
        ),
    ]
