# Generated by Django 5.0.3 on 2024-06-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_mealplan_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='page_title',
            field=models.CharField(default='dish', max_length=100),
        ),
    ]
