# Generated by Django 5.0.3 on 2024-06-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_mealplan_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='page_title',
            field=models.CharField(default='dish', max_length=1000),
        ),
    ]
