# Generated by Django 5.0.3 on 2024-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_alter_mealplan_page_title_alter_mealplan_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
