# Generated by Django 5.0.3 on 2024-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_alter_mealplan_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
