# Generated by Django 5.0.3 on 2024-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_alter_mealplan_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='photo',
            field=models.ImageField(max_length=2000, null=True, upload_to=''),
        ),
    ]
